# .air.toml
root = "."
tmp_dir = "tmp"

[build]
# Просто запускаем `go build -o ./tmp/main .`
cmd = "go build -buildvcs=false -o ./tmp/main ./cmd/main.go"
# Бинарный файл для запуска
bin = "tmp/main"
# Customizable binary.
full_bin = "./tmp/main"
# Следим за файлами с этими расширениями
include_ext = ["go", "tpl", "tmpl", "html"]
# Игнорируем эти директории
exclude_dir = ["assets", "tmp", "vendor"]
# Следим за файлами с этими именами
include_file = []
# Исключаем файлы с этими именами
exclude_file = []
# Задержка перед перезапуском
delay = 1000 # ms
# Убиваем процесс перед запуском нового
kill_delay = "0s"
# Отправляем Interrupt сигнал перед Kill
send_interrupt = false
# Останавливаем при ошибке
stop_on_error = true

[log]
# Показывать время
time = false

[color]
# Раскрашивать вывод
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Удалять tmp директорию при выходе
clean_on_exit = true